### ISSUE TITLE
Top Selectors are not working in transactions tab.

### ISSUE THREAD

**Issue by haseeb4091** [drkNsubuga/PharmaSpot#17]
![image](https://github.com/drkNsubuga/PharmaSpot/assets/74922363/5c20dcb6-7418-4e76-911f-c8d37ef0992b)

**Comment by drkNsubuga** [comment]
This seems to be working as expected. 

> ![image](https://private-user-images.githubusercontent.com/74922363/293016070-5c20dcb6-7418-4e76-911f-c8d37ef0992b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NDkyNzgsIm5iZiI6MTcwMzc0ODk3OCwicGF0aCI6Ii83NDkyMjM2My8yOTMwMTYwNzAtNWMyMGRjYjYtNzQxOC00ZTc2LTkxMWYtYzhkMzdlZjA5OTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDA3MzYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZTcxZWVhNTE2YTg4N2M2OGE3MzU5MDkyMzVmZjM1MDQ4YWM2NDk4NTg5YjM4NmVkYWUwY2E4MjFkZDkyODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LBFaX4twXtepPceqhMA-2nBBDnJa1czDU6faiclNdwY)

As per you filter, do you have any unpaid transactions? Have you tried to change the date filter to bigger date range like past 30 days?

**Comment by haseeb4091** [comment]
It is not working as i don't have unpaid transactions but it is showing all transaction.
Additionally Data Range is also not working.

**Comment by drkNsubuga** [comment]
I see...is the issue occuring in development mode or in a production version? Can you please provide an details on the environment? Do you see any specific errors in the console?

**Comment by drkNsubuga** [comment]
The issue has been closed because the feature is working in the latest version.
