### ISSUE TITLE
Problem with the developer version

### ISSUE THREAD

**Issue by dyahunter35** [drkNsubuga/PharmaSpot#22]
**Describe the bug**
when i need to run a dev version using npm or yarn 
I kept facing this problem:

<img width="495" alt="image" src="https://github.com/drkNsubuga/PharmaSpot/assets/23609385/5dbec50b-84b9-45bd-a059-0773d0cb1508">

**Comment by dyahunter35** [comment]
> Which OS are you currently running it from?

Mac OS Big Sur

**Comment by drkNsubuga** [comment]
> Mac OS Big Sur
 Confirm if the issue is fixed.

**Comment by drkNsubuga** [comment]
This has been fixed.
