### ISSUE TITLE
Print Bill issue

### ISSUE THREAD

**Issue by spideyO0** [drkNsubuga/PharmaSpot#29]
after bill generation the bill is nit getting printed but if i get into transactions and there print the bill it gets printed if any solutions or am i doing something wrong ?

**Comment by drkNsubuga** [comment]
Did you click the print button found on the bill?

**Comment by spideyO0** [comment]
> Did you click the print button found on the bill?

Ofc sir

**Comment by drkNsubuga** [comment]
> Ofc sir it's not showing me any popup or nothing when I clicked the button
I see.  Can you take me through the exact steps you are taking to print the receipt?

> Also is that button only supports thermal printer? cuz I am testing it on normal printer
You can use any printer.

**Comment by spideyO0** [comment]
> I see. Can you take me through the exact steps you are taking to print the receipt?
> 




> > Ofc sir it's not showing me any popup or nothing when I clicked the button
> 
> I see. Can you take me through the exact steps you are taking to print the receipt?
> 
> > Also is that button only supports thermal printer? cuz I am testing it on normal printer
> 
> You can use any printer.

Adding the products and then paid the bill the pop up of bill appeared with the print button but when I clicked the button nothing happened 

I can see the same button has been used under transactions bill section but that works only the pos button doesn't works also the transaction page bill shows the html rather than a styled bill

And print button before paying at the side of hold button is also not working for me

**Comment by drkNsubuga** [comment]
Just to confirm:
- Did you upload a logo in settings?
- Are you seeing any errors in the developer mode?

**Comment by spideyO0** [comment]
yeah after adding logo file correctly its working fine thanks for the help
