### ISSUE TITLE
Login problem 

### ISSUE THREAD

**Issue by thamizhthenvalavan** [drkNsubuga/PharmaSpot#40]
Not able to login with default username and password in executable file

**Comment by drkNsubuga** [comment]
Hi!
Can you provide more details please? Which Pharmaspot version are you using? How about the OS version?

**Comment by thamizhthenvalavan** [comment]
OS windows 8.1 and Pharmaspot versions  V.1.4.3, V.1.4.2 and V.1.4.1. I have tried all these versions with the default username: admin
password: admin 

I always get an error message Invalid username or password

**Comment by drkNsubuga** [comment]
The issue has been noted and will be fixed.
For the meantime, try to refresh the app. Click ```view > refresh``` or ```CTRL+R``` then enter the credentials. Keep refreshing until you are able to login.

**Comment by thamizhthenvalavan** [comment]
It works fine with windows 10
