### ISSUE TITLE
Stock limit showing even when minimum stock has not been reached and adding stock fails sometimes

### ISSUE THREAD

**Issue by AnoRebel** [drkNsubuga/PharmaSpot#42]
**Describe the bug**
1. Adding the stock was okay at first but after a while, I realized some of the stock added wasn't entered until I redid it again wonce or twice more sometimes, but it doesn't always occur so I cant exactly pinpoint the cause.
2. I initially added products without categories, then later added the categories and updated the products to add them to a category, after this process the minimum stock limit checker seems to have bugged out as it shows random products are in low stock even when their stock is high.

## Expected behavior
Everything to work as intended, products added once successfully and stock limit to be maintained.

## Actual Behavior
As described above

## Environment
- **Operating System:** Windows 10
- **Pharmaspot Version:** 1.4.3

**Comment by drkNsubuga** [comment]
Hi,
I cannot replicate the issue on my end. Can you please provide a video preview of the issue?

**Comment by AnoRebel** [comment]
I couldn't get a video, but I got images of how it looks.
The minimum stock for all of these is set to 5, but as you can see, even some with more than 100 in stock still complain about `Low Stock`
![stock](https://github.com/user-attachments/assets/767b567e-6855-49bc-992b-185492e3cf7a)
![stock1](https://github.com/user-attachments/assets/4b7f55eb-bcd4-4e48-b5ae-75c5cd0ed675)
